dist: trusty
language: node_js
node_js:
    - '8'
before_install:
    # setting the path for phantom.js 2.0.0
    - 'npm config set spin false'
    - 'npm install -g yarn'
install:
    - yarn install
script:
    - yarn test --coverage
